[env]
RESTART_WRITE=.true.

[namelist:files]
checkpoint_stem_name='restart-io_demo-'

[namelist:io]
checkpoint_times=60.0,120.0,240.0
checkpoint_write=.true.
end_of_run_checkpoint=.false.

[namelist:timestepping]
dt=10.0
