[env]
MPICH_MPIIO_AGGREGATOR_PLACEMENT_DISPLAY=1
MPICH_MPIIO_HINTS_DISPLAY=1
MPICH_MPIIO_STATS=1
VERNIER_OUTPUT_MODE=single

[namelist:io]
subroutine_timers=.true.
write_diag=.true.

[namelist:io_demo]
benchmark_sleep_time=1
io_benchmark=.true.
n_benchmark_fields=10

[namelist:time]
timestep_end='24'

[namelist:timestepping]
dt=3600.0
