[command]
default=$CORE_ROOT_DIR/bin/tweak_iodef ; \
       =$CORE_ROOT_DIR/bin/tweak_iodef temporal_context.xml; \
       =$LAUNCH_SCRIPT/launch-exe

[file:iodef.xml]
mode=auto
source=$ROSE_SUITE_DIR/app/io_demo/file/iodef_temporal.xml

[namelist:extrusion]
number_of_layers=70

[namelist:files]
temporal_file_path='$BIG_DATA_DIR/ancils/basic-gal/yak/$RESOLUTION/ozone/sparc/1994-2005/qrclim.ozone_L70_O70'

[namelist:io_demo]
temporal_reading=.true.

[namelist:timestepping]
dt=86400.0
